### PR TITLE
Add support for CUDA 11.2

### PR DESCRIPTION
**Pull request by saudet**
Fixes https://github.com/deeplearning4j/nd4j/issues/2936

I haven't tested the build, but there's no reason that it should fail given that it works with CUDA 11.1

/cc @camdenorrb @cyberbeat

### CODE REVIEW

**Comment by camdenorrb** [comment]
Unfortuantly I got this error on compile, could be my fault tho

```
In file included from /home/camdenorrb/Documents/Programming/Intellij/Libraries/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/jnind4jcpu.cpp:103:
/home/camdenorrb/Documents/Programming/Intellij/Libraries/deeplearning4j/libnd4j/include/cblas.h:25:10: fatal error: config.h: No such file or directory
   25 | #include "config.h"
      |          ^~~~~~~~~~
compilation terminated.
```

**Comment by cyberbeat** [comment]
I would be very glad if these changes would land in a beta8 as soon as possible to get the packages from maven-central

**Comment by quickwritereader** [comment]
```
./change-cuda-versions.sh 11.2
mvn clean install -Dmaven.test.skip -Dlibnd4j.chip=cuda -Dlibnd4j.cuda=11.2 -Dlibnd4j.compute=auto
```
the build was successful for me

**Review by quickwritereader — APPROVED** [review]
